/**
 * SQRRRDLE Game Socket Handlers
 *
 * Daily word guessing game with $qr currency rewards.
 * - Rewards: 5000 coins for first 3 tries, 1000 coins after
 * - Progress syncs across devices via MongoDB
 * - Prevents duplicate completions per 24 hours
 */

// Per-user transaction locks to prevent race conditions
const userLocks = new Map();

// Word list for daily word selection (same as frontend) - 5 and 6 letter words
const WORDS = [
  // Friends (Custom) - 5 letters
  'GARSI', 'KINUS', 'MOMIN', 'JESUS', 'KELMI', 'ASIER',

  // ===== 5-LETTER WORDS =====
  // LOL Champions (5 letters)
  'TEEMO', 'VAYNE', 'RIVEN', 'BRAND', 'NASUS', 'YASUO', 'SENNA', 'KAYLE',
  'TALON', 'DIANA', 'LEONA', 'JANNA', 'ANNIE', 'FIORA', 'JAYCE', 'AKALI',
  'KARMA', 'ZIGGS', 'QUINN', 'BRAUM', 'SYLAS', 'YUUMI', 'GAREN', 'VIEGO',
  'VARUS', 'URGOT', 'POPPY', 'ELISE', 'SWAIN', 'SHACO', 'TARIC', 'SIVIR',
  'CORKI', 'AMUMU', 'GALIO', 'IVERN', 'MILIO', 'NEEKO', 'NILAH', 'RAKAN',
  'XAYAH', 'NASUS', 'VEIGAR',

  // Overwatch (5 letters)
  'GENJI', 'HANZO', 'MERCY', 'ZARYA', 'SIGMA', 'LUCIO', 'ORISA', 'MOIRA',

  // Nintendo (5 letters)
  'MARIO', 'LUIGI', 'ZELDA', 'KIRBY', 'WARIO', 'PEACH', 'YOSHI', 'SAMUS',
  'GANON', 'KOOPA', 'DAISY', 'DIDDY', 'FALCO', 'SHULK', 'MARTH', 'ROBIN',
  'CHROM', 'LUCAS', 'EPONA', 'MIDNA', 'MIPHA', 'DARUK', 'SIDON',

  // Pokemon (5 letters)
  'PICHU', 'EEVEE', 'DITTO', 'ZUBAT', 'RALTS', 'SHINX', 'LUXIO', 'ZORUA',
  'LUGIA', 'ENTEI', 'ABSOL', 'ARBOK', 'EKANS', 'ABRA',

  // Sonic (5 letters)
  'SONIC', 'TAILS', 'ROUGE', 'BLAZE', 'METAL', 'KNUCKLES',

  // Final Fantasy (5 letters)
  'CLOUD', 'TIDUS', 'AURON', 'AERIS', 'SQUALL',

  // Street Fighter / Fighting Games (5 letters)
  'GUILE', 'CAMMY', 'SAGAT', 'BISON', 'AKUMA', 'IBUKI', 'KARIN',
  'SONYA', 'ERMAC', 'ASUKA', 'ALISA', 'BRYAN',

  // Other Famous Game Characters (5 letters)
  'SNAKE', 'CRASH', 'SPYRO', 'DANTE', 'STEVE', 'JOKER', 'ELLIE',
  'CHIEF', 'QUIET', 'SOLID', 'LARA',

  // Game Names (5 letters)
  'HADES', 'BRAWL', 'SMASH', 'LIMBO', 'FORZA', 'GEARS', 'FABLE',
  'OKAMI', 'STRAY', 'TUNIC', 'BRAID', 'ISAAC', 'AMONG',

  // Gaming Terms (5 letters)
  'COMBO', 'SPAWN', 'BONUS', 'LEVEL', 'ARMOR', 'SKILL', 'LOBBY',
  'KILLS', 'SWORD', 'MAGIC', 'HEALS', 'MAINS', 'PATCH', 'RANKS', 'STATS',
  'BUILD', 'FLASH', 'GHOST', 'SMITE', 'BARON', 'DRAKE', 'NEXUS', 'GAMER',
  'TOWER', 'CARRY', 'CHAMP', 'ITEMS', 'RESET',

  // ===== 6-LETTER WORDS =====
  // LOL Champions (6 letters)
  'THRESH', 'VIKTOR', 'ANIVIA', 'ZILEAN', 'SINGED', 'RAMMUS', 'GRAVES',
  'IRELIA', 'EZREAL', 'SORAKA', 'DRAVEN', 'RENGAR', 'RUMBLE', 'KENNEN',
  'TWITCH', 'VEIGAR', 'XERATH', 'KASSADIN',

  // Overwatch (6 letters)
  'TRACER', 'REAPER', 'SOMBRA', 'PHARAH', 'TORBJORN',

  // Nintendo (6 letters)
  'BOWSER', 'FALCON', 'TINGLE', 'URBOSA', 'REVALI', 'OLIMAR', 'PIKMIN',
  'BYLETH', 'MYTHRA', 'RIDLEY',

  // Pokemon (6 letters)
  'GENGAR', 'MEWTWO', 'ARCEUS', 'VULPIX', 'MUDKIP', 'GASTLY', 'MEOWTH',
  'LAPRAS', 'CELEBI', 'KYOGRE', 'DIALGA', 'PALKIA', 'WOBBUFFET',

  // Final Fantasy / JRPG (6 letters)
  'NOCTIS', 'SEPHIROTH',

  // Street Fighter / Fighting Games (6 letters)
  'BLANKA', 'BALROG', 'SAKURA', 'RASHID', 'JOHNNY', 'KITANA', 'BARAKA',
  'KAZUYA', 'RAIDEN',

  // Other Famous Game Characters (6 letters)
  'KRATOS', 'NATHAN', 'TREVOR', 'ARTHUR', 'GERALT', 'OCELOT', 'LIQUID',
  'MASTER', 'CORTANA',

  // Game Names (6 letters)
  'PORTAL', 'TETRIS', 'SKYRIM', 'DIABLO', 'SEKIRO', 'HITMAN', 'ROBLOX',
  'RAYMAN', 'TEKKEN', 'LEAGUE', 'YAKUZA', 'HOLLOW', 'ROCKET', 'INSIDE',
  'TARKOV', 'ANTHEM',

  // Gaming Terms (6 letters)
  'DAMAGE', 'SHIELD', 'HEALTH', 'MINION', 'CREEPS', 'RANKED', 'JUNGLE',
];

// Filter to only valid 5 and 6 letter words
const WORDS_CLEAN = WORDS.filter(w => w.length === 5 || w.length === 6);

// Extended valid guesses - comprehensive English and Spanish word lists
const VALID_GUESSES = new Set([
  ...WORDS_CLEAN,
  // ===== 5-LETTER ENGLISH WORDS =====
  'ABOUT', 'ABOVE', 'ABUSE', 'ACTOR', 'ACUTE', 'ADMIT', 'ADOPT', 'ADULT',
  'AFTER', 'AGAIN', 'AGENT', 'AGREE', 'AHEAD', 'ALARM', 'ALBUM', 'ALERT',
  'ALIKE', 'ALIVE', 'ALLOW', 'ALONE', 'ALONG', 'ALTER', 'AMONG', 'ANGER',
  'ANGLE', 'ANGRY', 'APART', 'APPLE', 'APPLY', 'ARENA', 'ARGUE', 'ARISE',
  'ARRAY', 'ASIDE', 'ASSET', 'AUDIO', 'AVOID', 'AWARD', 'AWARE', 'AWFUL',
  'BACON', 'BADGE', 'BADLY', 'BAKER', 'BASES', 'BASIC', 'BASIS', 'BATCH',
  'BEACH', 'BEARD', 'BEAST', 'BEGAN', 'BEGIN', 'BEGUN', 'BEING', 'BELLY',
  'BELOW', 'BENCH', 'BERRY', 'BIRTH', 'BLACK', 'BLADE', 'BLAME',
  'BLANK', 'BLAST', 'BLAZE', 'BLEED', 'BLEND', 'BLESS', 'BLIND', 'BLINK',
  'BLISS', 'BLOCK', 'BLOND', 'BLOOD', 'BLOOM', 'BLOWN', 'BLUES', 'BLUNT',
  'BLUSH', 'BOARD', 'BOAST', 'BONUS', 'BOOST', 'BOOTH', 'BORED', 'BOUND',
  'BOXER', 'BRAIN', 'BRAKE', 'BRAND', 'BRASS', 'BRAVE', 'BREAD', 'BREAK',
  'BREED', 'BRICK', 'BRIDE', 'BRIEF', 'BRING', 'BROAD', 'BROKE', 'BROOK',
  'BROOM', 'BROWN', 'BRUSH', 'BUILD', 'BUILT', 'BUNCH', 'BURNT', 'BURST',
  'BUYER', 'CABIN', 'CABLE', 'CACHE', 'CAMEL', 'CANDY', 'CANON', 'CARGO',
  'CARRY', 'CARVE', 'CATCH', 'CAUSE', 'CEASE', 'CHAIN', 'CHAIR', 'CHAOS',
  'CHARM', 'CHART', 'CHASE', 'CHEAP', 'CHEAT', 'CHECK', 'CHEEK', 'CHEER',
  'CHESS', 'CHEST', 'CHICK', 'CHIEF', 'CHILD', 'CHILL', 'CHINA', 'CHIPS',
  'CHOIR', 'CHORD', 'CHOSE', 'CHUNK', 'CIGAR', 'CINCH', 'CIRCA', 'CIVIL',
  'CLAIM', 'CLAMP', 'CLASH', 'CLASP', 'CLASS', 'CLEAN', 'CLEAR', 'CLERK',
  'CLICK', 'CLIFF', 'CLIMB', 'CLING', 'CLOCK', 'CLONE', 'CLOSE', 'CLOTH',
  'CLOUD', 'CLOWN', 'COACH', 'COAST', 'COBRA', 'COLON', 'COLOR', 'COMET',
  'CORAL', 'COUCH', 'COUGH', 'COULD', 'COUNT', 'COUPE', 'COURT', 'COVER',
  'CRACK', 'CRAFT', 'CRANE', 'CRASH', 'CRATE', 'CRAWL', 'CRAZE', 'CRAZY',
  'CREAM', 'CREEK', 'CREEP', 'CREST', 'CRIME', 'CRISP', 'CROSS', 'CROWD',
  'CROWN', 'CRUDE', 'CRUEL', 'CRUSH', 'CRUST', 'CURLY', 'CURRY', 'CURSE',
  'CURVE', 'CYCLE', 'DADDY', 'DAILY', 'DAIRY', 'DAISY', 'DANCE', 'DATED',
  'DEALT', 'DEATH', 'DEBUT', 'DECAY', 'DECOR', 'DECOY', 'DELAY', 'DELTA',
  'DEMON', 'DENIM', 'DENSE', 'DEPOT', 'DEPTH', 'DERBY', 'DETOX',
  'DEVIL', 'DIARY', 'DIGIT', 'DINER', 'DIRTY', 'DISCO', 'DITCH', 'DIVER',
  'DIZZY', 'DOING', 'DONOR', 'DONUT', 'DOUBT', 'DOUGH', 'DOZEN', 'DRAFT',
  'DRAIN', 'DRAKE', 'DRAMA', 'DRANK', 'DRAPE', 'DRAWN', 'DREAD', 'DREAM',
  'DRESS', 'DRIED', 'DRIFT', 'DRILL', 'DRINK', 'DRIVE', 'DROIT', 'DROWN',
  'DROVE', 'DRUNK', 'DWELL', 'DYING', 'EAGER', 'EAGLE', 'EARLY', 'EARTH',
  'EATEN', 'EATER', 'EIGHT', 'ELBOW', 'ELDER', 'ELECT', 'ELITE',
  'EMAIL', 'EMBED', 'EMBER', 'EMPTY', 'ENDED', 'ENEMY', 'ENJOY', 'ENTER',
  'ENTRY', 'ENVOY', 'EQUAL', 'EQUIP', 'ERROR', 'ESSAY', 'ETHIC', 'EVENT',
  'EVERY', 'EXACT', 'EXAMS', 'EXCEL', 'EXIST', 'EXTRA', 'FABLE', 'FACET',
  'FACTO', 'FAINT', 'FAIRY', 'FAITH', 'FALSE', 'FANCY', 'FATAL', 'FATTY',
  'FAULT', 'FAUNA', 'FAVOR', 'FEAST', 'FERRY', 'FETCH', 'FEVER', 'FIBER',
  'FIBRE', 'FIELD', 'FIERY', 'FIFTH', 'FIFTY', 'FIGHT', 'FILTH', 'FINAL',
  'FINCH', 'FIRST', 'FIXED', 'FIXER', 'FLAGS', 'FLAIR', 'FLAKE', 'FLAME',
  'FLANK', 'FLARE', 'FLASH', 'FLASK', 'FLOOD', 'FLOOR', 'FLORA', 'FLOUR',
  'FLOWN', 'FLUID', 'FLUKE', 'FLUNG', 'FLUSH', 'FLUTE', 'FOCAL', 'FOCUS',
  'FOGGY', 'FORCE', 'FORGE', 'FORTH', 'FORTY', 'FORUM', 'FOUND',
  'FRAME', 'FRANK', 'FRAUD', 'FREAK', 'FRESH', 'FRIAR', 'FRIED', 'FRIES',
  'FRONT', 'FROST', 'FRUIT', 'FULLY', 'FUNGI', 'FUNKY', 'FUNNY', 'FUZZY',
  'GAMMA', 'GAUGE', 'GEESE', 'GENRE', 'GHOST', 'GIANT', 'GIVEN', 'GIVER',
  'GLAND', 'GLARE', 'GLASS', 'GLAZE', 'GLEAM', 'GLIDE', 'GLOBE', 'GLOOM',
  'GLORY', 'GLOSS', 'GLOVE', 'GOING', 'GOODS', 'GOOSE', 'GORGE', 'GRACE',
  'GRADE', 'GRAIN', 'GRAND', 'GRANT', 'GRAPE', 'GRAPH', 'GRASP', 'GRASS',
  'GRAVE', 'GRAVY', 'GRAZE', 'GREAT', 'GREED', 'GREEN', 'GREET', 'GRIEF',
  'GRILL', 'GRIND', 'GROAN', 'GROOM', 'GROSS', 'GROUP', 'GROVE', 'GROWL',
  'GROWN', 'GUARD', 'GUESS', 'GUEST', 'GUIDE', 'GUILD', 'GUILT', 'GUISE',
  'GUMMY', 'HABIT', 'HAIRY', 'HANDY', 'HAPPY', 'HARSH', 'HASTE', 'HASTY',
  'HATCH', 'HAVEN', 'HAZEL', 'HEADS', 'HEARD', 'HEART', 'HEATH', 'HEAVY',
  'HEDGE', 'HEELS', 'HEIST', 'HELLO', 'HENCE', 'HERBS', 'HERON', 'HILLS',
  'HINGE', 'HIPPO', 'HOBBY', 'HOMER', 'HONEY', 'HONOR', 'HORSE', 'HOUND',
  'HOURS', 'HOUSE', 'HOVER', 'HUMAN', 'HUMID', 'HUMOR', 'HURRY', 'HYENA',
  'IDEAL', 'IMAGE', 'IMPLY', 'INDEX', 'INDIE', 'INNER', 'INPUT', 'INTRO',
  'IONIC', 'IRONY', 'ISSUE', 'IVORY', 'JELLY', 'JERRY', 'JETTY', 'JEWEL',
  'JIFFY', 'JOINT', 'JOKER', 'JOLLY', 'JONES', 'JUDGE', 'JUICE', 'JUICY',
  'JUMBO', 'JUMPY', 'KARMA', 'KAYAK', 'KEBAB', 'KEEPS', 'KETCH', 'KICKS',
  'KINGS', 'KIOSK', 'KITTY', 'KNACK', 'KNEAD', 'KNEEL', 'KNELT', 'KNIFE',
  'KNOCK', 'KNOWN', 'LABEL', 'LABOR', 'LAGER', 'LANCE', 'LANDS', 'LARGE',
  'LARRY', 'LASER', 'LATCH', 'LATER', 'LATEX', 'LATIN', 'LAUGH', 'LAYER',
  'LEARN', 'LEASE', 'LEAST', 'LEAVE', 'LEDGE', 'LEGAL', 'LEMON', 'LEMUR',
  'LEVEL', 'LEVER', 'LIGHT', 'LIMBO', 'LIMIT', 'LINED', 'LINEN', 'LINER',
  'LINKS', 'LIONS', 'LISTS', 'LITER', 'LIVER', 'LIVES', 'LLAMA', 'LOADS',
  'LOANS', 'LOCAL', 'LOCUS', 'LODGE', 'LOFTY', 'LOGIC', 'LOGOS', 'LOOKS',
  'LOOPS', 'LOOSE', 'LORDS', 'LORRY', 'LOSER', 'LOTUS', 'LOVED', 'LOVER',
  'LOWER', 'LOYAL', 'LUCKY', 'LUNAR', 'LUNCH', 'LUNGS', 'LYING', 'LYMPH',
  'LYRIC', 'MACRO', 'MAFIA', 'MAGIC', 'MAGMA', 'MAJOR', 'MAKER', 'MANGA',
  'MANGO', 'MANOR', 'MAPLE', 'MARCH', 'MARRY', 'MARSH', 'MATCH', 'MATHS',
  'MAYOR', 'MEATY', 'MEDAL', 'MEDIA', 'MELON', 'MERCY', 'MERGE', 'MERIT',
  'MERRY', 'MESSY', 'METAL', 'METER', 'METRO', 'MICRO', 'MIDST', 'MIGHT',
  'MILLS', 'MIMIC', 'MINCE', 'MINDS', 'MINOR', 'MINUS', 'MISTY', 'MIXER',
  'MODEL', 'MODEM', 'MODES', 'MOIST', 'MOLAR', 'MONEY', 'MONTH', 'MOODY',
  'MORAL', 'MOTOR', 'MOTTO', 'MOULD', 'MOUND', 'MOUNT', 'MOURN', 'MOUSE',
  'MOUTH', 'MOVED', 'MOVER', 'MOVIE', 'MUDDY', 'MULTI', 'MUMMY', 'MURAL',
  'MUSIC', 'MUSTY', 'NAIVE', 'NAMED', 'NANNY', 'NASAL', 'NASTY', 'NAVAL',
  'NEEDS', 'NERVE', 'NEVER', 'NEWER', 'NEWLY', 'NEXUS', 'NICER', 'NICHE',
  'NIGHT', 'NINJA', 'NINTH', 'NOBLE', 'NODAL', 'NODES', 'NOISE', 'NOISY',
  'NOMAD', 'NORMS', 'NORTH', 'NOTCH', 'NOTED', 'NOTES', 'NOVEL', 'NURSE',
  'OCCUR', 'OCEAN', 'ODDLY', 'OFFER', 'OFTEN', 'OLIVE', 'OMEGA', 'ONSET',
  'OPENS', 'OPERA', 'OPTIC', 'ORBIT', 'ORDER', 'ORGAN', 'OTHER', 'OTTER',
  'OUGHT', 'OUNCE', 'OUTER', 'OUTGO', 'OWNED', 'OWNER', 'OXIDE', 'OZONE',
  'PACKS', 'PADRE', 'PAGAN', 'PAGES', 'PAINT', 'PAIRS', 'PANEL', 'PANIC',
  'PAPER', 'PARKS', 'PARTS', 'PARTY', 'PASTA', 'PASTE', 'PATCH', 'PATHS',
  'PATIO', 'PAUSE', 'PAYEE', 'PEACE', 'PEACH', 'PEAKS', 'PEARL', 'PEERS',
  'PENNY', 'PERCH', 'PERIL', 'PERKY', 'PESTO', 'PETTY', 'PHASE', 'PHONE',
  'PHOTO', 'PIANO', 'PIECE', 'PIETY', 'PIGGY', 'PILOT', 'PINCH', 'PIPER',
  'PITCH', 'PIVOT', 'PIXEL', 'PIZZA', 'PLACE', 'PLAID', 'PLAIN', 'PLANE',
  'PLANK', 'PLANS', 'PLANT', 'PLATE', 'PLAZA', 'PLEAD', 'PLEAT', 'PLUCK',
  'PLUMB', 'PLUME', 'PLUMP', 'PLUSH', 'POEMS', 'POETS', 'POINT', 'POLAR',
  'POLLS', 'POOLS', 'PORCH', 'PORES', 'PORTS', 'POSED', 'POSER', 'POSTS',
  'POUCH', 'POUND', 'POWER', 'PRANK', 'PRAWN', 'PRESS', 'PRICE', 'PRICK',
  'PRIDE', 'PRIME', 'PRINT', 'PRIOR', 'PRISM', 'PRIVY', 'PRIZE', 'PROBE',
  'PROMO', 'PRONE', 'PROOF', 'PROSE', 'PROUD', 'PROVE', 'PROXY', 'PRUNE',
  'PSALM', 'PUBIC', 'PULSE', 'PUNCH', 'PUPIL', 'PUPPY', 'PURSE', 'QUACK',
  'QUART', 'QUEEN', 'QUERY', 'QUEST', 'QUEUE', 'QUICK', 'QUIET', 'QUILT',
  'QUIRK', 'QUITE', 'QUOTA', 'QUOTE', 'RADAR', 'RADIO', 'RAINY', 'RAISE',
  'RALLY', 'RANCH', 'RANGE', 'RANKS', 'RAPID', 'RARER', 'RATED', 'RATES',
  'RATIO', 'RAZOR', 'REACH', 'REACT', 'READS', 'READY', 'REALM', 'REBEL',
  'RECAP', 'REFER', 'REGAL', 'REIGN', 'RELAX', 'RELAY', 'RELIC', 'REMIT',
  'RENAL', 'RENEW', 'REPLY', 'RESET', 'RESIN', 'RETRO', 'RHINO', 'RIDGE',
  'RIFLE', 'RIGID', 'RIGOR', 'RINGS', 'RINSE', 'RIPEN', 'RISEN', 'RISER',
  'RISKS', 'RISKY', 'RITON', 'RIVAL', 'RIVER', 'ROADS', 'ROAST',
  'ROBOT', 'ROCKY', 'ROGER', 'ROGUE', 'ROLES', 'ROMAN', 'ROOFS', 'ROOMS',
  'ROOTS', 'ROPES', 'ROSES', 'ROTOR', 'ROUGE', 'ROUGH', 'ROUND', 'ROUTE',
  'ROVER', 'ROWDY', 'ROYAL', 'RUGBY', 'RUINS', 'RULER', 'RULES', 'RUMOR',
  'RURAL', 'RUSTY', 'SADLY', 'SAFER', 'SAINT', 'SALAD', 'SALES', 'SALLY',
  'SALON', 'SALSA', 'SALTY', 'SALVE', 'SAMBA', 'SANDY', 'SANER', 'SANTA',
  'SAUCE', 'SAUNA', 'SAVOR', 'SAVVY', 'SCALD', 'SCALE', 'SCALP', 'SCALY',
  'SCAMP', 'SCANT', 'SCARE', 'SCARF', 'SCARY', 'SCENE', 'SCENT', 'SCOPE',
  'SCORE', 'SCORN', 'SCOUT', 'SCRAP', 'SCREW', 'SEAMS', 'SEATS', 'SEEDS',
  'SEEMS', 'SEIZE', 'SEMIS', 'SENDS', 'SENSE', 'SERUM', 'SERVE', 'SETUP',
  'SEVEN', 'SEVER', 'SHADE', 'SHADY', 'SHAFT', 'SHAKE', 'SHAKY', 'SHALL',
  'SHAME', 'SHAPE', 'SHARE', 'SHARK', 'SHARP', 'SHAVE', 'SHEAR', 'SHEDS',
  'SHEEN', 'SHEEP', 'SHEER', 'SHEET', 'SHELF', 'SHELL', 'SHIFT', 'SHINE',
  'SHINY', 'SHIPS', 'SHIRE', 'SHIRT', 'SHOCK', 'SHOES', 'SHONE', 'SHOOK',
  'SHOOT', 'SHOPS', 'SHORE', 'SHORT', 'SHOTS', 'SHOUT', 'SHOWN', 'SHOWS',
  'SHRUG', 'SIDES', 'SIEGE', 'SIGHT', 'SIGMA', 'SIGNS', 'SILKY', 'SILLY',
  'SINCE', 'SIREN', 'SITES', 'SIXTH', 'SIXTY', 'SIZED', 'SIZES', 'SKATE',
  'SKILL', 'SKIMP', 'SKINS', 'SKIRT', 'SKULL', 'SLABS', 'SLACK', 'SLAIN',
  'SLANT', 'SLASH', 'SLATE', 'SLAVE', 'SLEEK', 'SLEEP', 'SLICE', 'SLIDE',
  'SLIME', 'SLIMY', 'SLING', 'SLOPE', 'SLOTS', 'SLUMP', 'SMALL', 'SMART',
  'SMASH', 'SMELL', 'SMILE', 'SMIRK', 'SMOKE', 'SMOKY', 'SNACK', 'SNAIL',
  'SNAKE', 'SNARE', 'SNEAK', 'SNIFF', 'SNORE', 'SNORT', 'SNOWY', 'SOAPY',
  'SOBER', 'SOLAR', 'SOLEM', 'SOLID', 'SOLVE', 'SONIC', 'SONGS', 'SORRY',
  'SORTS', 'SOULS', 'SOUND', 'SOUTH', 'SPACE', 'SPADE', 'SPARE', 'SPARK',
  'SPAWN', 'SPEAK', 'SPEAR', 'SPECS', 'SPEED', 'SPELL', 'SPEND', 'SPENT',
  'SPICE', 'SPICY', 'SPIKE', 'SPILL', 'SPINE', 'SPOKE', 'SPOON', 'SPORT',
  'SPOTS', 'SPRAY', 'SQUAD', 'STACK', 'STAFF', 'STAGE', 'STAIN', 'STAIR',
  'STAKE', 'STALE', 'STALK', 'STALL', 'STAMP', 'STAND', 'STANK', 'STARK',
  'STARS', 'START', 'STASH', 'STATE', 'STAYS', 'STEAK', 'STEAL', 'STEAM',
  'STEEL', 'STEEP', 'STEER', 'STEMS', 'STEPS', 'STERN', 'STICK', 'STIFF',
  'STILL', 'STING', 'STINK', 'STINT', 'STOCK', 'STOIC', 'STOKE', 'STOLE',
  'STOMP', 'STONE', 'STOOD', 'STOOL', 'STOOP', 'STOPS', 'STORE', 'STORM',
  'STORY', 'STOUT', 'STOVE', 'STRAP', 'STRAW', 'STRAY', 'STRIP', 'STRUM',
  'STRUT', 'STUCK', 'STUDY', 'STUFF', 'STUMP', 'STUNG', 'STUNK', 'STUNT',
  'STYLE', 'SUGAR', 'SUITE', 'SUITS', 'SUNNY', 'SUPER', 'SURGE', 'SUSHI',
  'SWAMP', 'SWANS', 'SWARM', 'SWEAR', 'SWEAT', 'SWEEP', 'SWEET', 'SWEPT',
  'SWIFT', 'SWING', 'SWIPE', 'SWIRL', 'SWISS', 'SWORD', 'SWORE', 'SWORN',
  'SWUNG', 'SYNOD', 'SYRUP', 'TABLE', 'TABOO', 'TACIT', 'TAKEN', 'TALES',
  'TALKS', 'TALLY', 'TANGO', 'TANGY', 'TANKS', 'TARDY', 'TASTE', 'TASTY',
  'TAXES', 'TEACH', 'TEAMS', 'TEARS', 'TEENS', 'TEETH', 'TEMPO', 'TENDS',
  'TENOR', 'TENSE', 'TENTH', 'TENTS', 'TERMS', 'TERRA', 'TESTS', 'TEXTS',
  'THANK', 'THEFT', 'THEIR', 'THEME', 'THERE', 'THESE', 'THICK', 'THIEF',
  'THIGH', 'THING', 'THINK', 'THIRD', 'THOSE', 'THREE', 'THREW', 'THROW',
  'THRUM', 'THUMB', 'TIDAL', 'TIGER', 'TIGHT', 'TILES', 'TILTS', 'TIMER',
  'TIMES', 'TIMID', 'TIPSY', 'TIRED', 'TITAN', 'TITLE', 'TOAST', 'TODAY',
  'TOKEN', 'TONAL', 'TONED', 'TONER', 'TONGS', 'TONIC', 'TOOLS', 'TOOTH',
  'TOPIC', 'TORCH', 'TORSO', 'TOTAL', 'TOTEM', 'TOUCH', 'TOUGH', 'TOURS',
  'TOWEL', 'TOWER', 'TOWNS', 'TOXIC', 'TRACE', 'TRACK', 'TRACT', 'TRADE',
  'TRAIL', 'TRAIN', 'TRAIT', 'TRAMP', 'TRASH', 'TRAWL', 'TREAD', 'TREAT',
  'TREES', 'TREND', 'TRIAL', 'TRIBE', 'TRICK', 'TRIED', 'TRIES', 'TRIKE',
  'TRIMS', 'TRIPS', 'TRITE', 'TROLL', 'TROOP', 'TROUT', 'TRUCE', 'TRUCK',
  'TRULY', 'TRUMP', 'TRUNK', 'TRUST', 'TRUTH', 'TUBES', 'TULIP', 'TUMOR',
  'TUNED', 'TUNER', 'TUNES', 'TUNIC', 'TURBO', 'TURNS', 'TUTOR', 'TWEAK',
  'TWEED', 'TWICE', 'TWIGS', 'TWINE', 'TWINS', 'TWIRL', 'TWIST', 'TYPED',
  'TYPES', 'UDDER', 'ULCER', 'ULTRA', 'UNCLE', 'UNDER', 'UNDID', 'UNDUE',
  'UNFIT', 'UNIFY', 'UNION', 'UNITE', 'UNITS', 'UNITY', 'UNMET', 'UNTIL',
  'UPPER', 'UPSET', 'URBAN', 'URGED', 'URINE', 'USAGE', 'USERS', 'USHER',
  'USING', 'USUAL', 'UTTER', 'VAGUE', 'VALID', 'VALOR', 'VALUE', 'VALVE',
  'VAPOR', 'VAULT', 'VEGAS', 'VEGAN', 'VEINS', 'VENOM', 'VENUE', 'VERBS',
  'VERGE', 'VERSE', 'VIDEO', 'VIEWS', 'VIGOR', 'VILLA', 'VINYL', 'VIOLA',
  'VIPER', 'VIRAL', 'VIRUS', 'VISIT', 'VISOR', 'VISTA', 'VITAL', 'VIVID',
  'VOCAL', 'VODKA', 'VOGUE', 'VOICE', 'VOILA', 'VOLTS', 'VOMIT', 'VOTED',
  'VOTER', 'VOTES', 'VOUCH', 'VOWEL', 'WACKY', 'WADED', 'WADER', 'WAFER',
  'WAGER', 'WAGES', 'WAGON', 'WAIST', 'WALKS', 'WALLS', 'WALTZ', 'WANDS',
  'WANTS', 'WARDS', 'WARES', 'WARNS', 'WASTE', 'WATCH', 'WATER', 'WAVED',
  'WAVER', 'WAVES', 'WEARY', 'WEAVE', 'WEDGE', 'WEEDS', 'WEEKS', 'WEIGH',
  'WEIRD', 'WELLS', 'WELSH', 'WETLY', 'WHALE', 'WHARF', 'WHEAT', 'WHEEL',
  'WHERE', 'WHICH', 'WHILE', 'WHINE', 'WHIRL', 'WHITE', 'WHOLE', 'WHOSE',
  'WIDEN', 'WIDER', 'WIDOW', 'WIDTH', 'WIELD', 'WINES', 'WINGS', 'WIPED',
  'WIPER', 'WIRED', 'WIRES', 'WITCH', 'WITTY', 'WOKEN', 'WOMAN', 'WOMEN',
  'WOODS', 'WOODY', 'WORDS', 'WORKS', 'WORLD', 'WORMS', 'WORRY', 'WORSE',
  'WORST', 'WORTH', 'WOULD', 'WOUND', 'WOVEN', 'WRAPS', 'WRATH', 'WRECK',
  'WREST', 'WRIST', 'WRITE', 'WRONG', 'WROTE', 'YACHT', 'YEARS', 'YEAST',
  'YIELD', 'YOUNG', 'YOURS', 'YOUTH', 'ZEBRA', 'ZESTY', 'ZONES',
  // ===== 5-LETTER SPANISH WORDS =====
  'ABAJO', 'ABRIL', 'ABRIR', 'ACABA', 'ACASO', 'ACERO', 'ACIDO', 'ACTOS',
  'ACTUA', 'ACTOR', 'ACUTE', 'ADIOS', 'ADOBE', 'AFINA', 'AGUAS', 'AHORA',
  'AIRES', 'AJENO', 'AJUAR', 'ALBUM', 'ALDEA', 'ALEJA', 'ALGOS', 'ALGUN',
  'ALIAS', 'ALIEN', 'ALISO', 'ALMAS', 'ALTAR', 'ALTOS', 'AMABA', 'AMADO',
  'AMAGO', 'AMANO', 'AMARA', 'AMBAR', 'AMBOS', 'AMENO', 'AMIGA', 'AMIGO',
  'ANCLA', 'ANEXO', 'ANGEL', 'ANIMA', 'ANIMO', 'ANTES', 'AQUEL', 'ARABE',
  'ARBOL', 'ARDEN', 'AREAS', 'ARENA', 'ARMAR', 'AROMA', 'ARRAY', 'ARROZ',
  'ARTES', 'ASADO', 'ASILO', 'ASOMA', 'ATLAS', 'ATOMO', 'AUDIO', 'AVENA',
  'AVION', 'AVISO', 'AYUDA', 'AYUNO', 'AZOTE', 'BAILA', 'BAILE', 'BAJAR',
  'BAJAS', 'BAJOS', 'BANCA', 'BANCO', 'BANDA', 'BANDO', 'BARRA', 'BARON',
  'BARCO', 'BASES', 'BASTA', 'BATEA', 'BATIR', 'BEBER', 'BELGA', 'BELLA',
  'BELLO', 'BESAR', 'BICHO', 'BINGO', 'BIOMA', 'BLANC', 'BLUES', 'BOBOS',
  'BOCAS', 'BODAS', 'BOLAS', 'BOLSA', 'BOMBA', 'BORDE', 'BORRA', 'BOTAS',
  'BOTES', 'BRAVO', 'BRAZO', 'BREVE', 'BRISA', 'BRUJA', 'BRUJO', 'BRUMA',
  'BRUTA', 'BRUTO', 'BUENA', 'BUENO', 'BUHOS', 'BULTO', 'BURLA', 'BUSCA',
  'BUZON', 'CABAL', 'CABER', 'CABOS', 'CABRA', 'CACHE', 'CACHO', 'CAERA',
  'CAIDA', 'CAJAS', 'CALCE', 'CALDO', 'CALMA', 'CALOR', 'CALVA', 'CALVO',
  'CAMAS', 'CAMPO', 'CANAL', 'CANAS', 'CANTO', 'CAPAZ', 'CAPEA', 'CARGA',
  'CARNE', 'CAROS', 'CARTA', 'CASAS', 'CASOS', 'CASTA', 'CASTO', 'CAUSA',
  'CAVAR', 'CAZAS', 'CEDER', 'CEJAS', 'CELDA', 'CELOS', 'CENAS', 'CENSO',
  'CERCA', 'CERDO', 'CEROS', 'CESAR', 'CHALE', 'CHAPA', 'CHICA', 'CHICO',
  'CHILE', 'CHINA', 'CHINO', 'CHIVO', 'CHOCA', 'CIEGA', 'CIEGO', 'CIELO',
  'CIFRA', 'CINCO', 'CINES', 'CINTA', 'CIRCO', 'CISCO', 'CITAS', 'CIVIL',
  'CLARA', 'CLARO', 'CLASE', 'CLAVE', 'CLAVO', 'CLIMA', 'COCHE', 'COGER',
  'COJIN', 'COLAS', 'COLOR', 'COMAS', 'COMBO', 'COMER', 'COMIA', 'COMOS',
  'COMUN', 'CONDE', 'CONGA', 'COPIA', 'COPAS', 'CORAL', 'CORAN', 'CORRA',
  'CORRE', 'CORTA', 'CORTE', 'CORTO', 'COSAS', 'COSTA', 'COSTO', 'CREAN',
  'CREAR', 'CRECE', 'CREMA', 'CRIAN', 'CRUDA', 'CRUDO', 'CRUEL', 'CRUJE',
  'CUAJE', 'CUAJO', 'CUATE', 'CUBOS', 'CUECE', 'CUERO', 'CUEVA', 'CULPA',
  'CULTO', 'CUNDE', 'CURAS', 'CURSA', 'CURSO', 'CURVA', 'DADOS', 'DAMAS',
  'DANDO', 'DANZA', 'DANAR', 'DATOS', 'DEBER', 'DEBIL', 'DECIR', 'DEDAL',
  'DEDOS', 'DEJAR', 'DELTA', 'DEMAS', 'DENSO', 'DESDE', 'DESEO', 'DICHA',
  'DICHO', 'DIEGO', 'DIGNA', 'DIGNO', 'DISCO', 'DISTE', 'DIVAN', 'DOBLE',
  'DOCIL', 'DOLOR', 'DOMAR', 'DONDE', 'DONAR', 'DORAR', 'DOSIS', 'DOTAR',
  'DROGA', 'DUCHA', 'DUDAR', 'DUDAS', 'DUELO', 'DUENA', 'DUENO', 'DULCE',
  'DURAS', 'DUROS', 'ECHAR', 'ELIJE', 'ELITE', 'ELLOS', 'EMAIL', 'EMITE',
  'ENANO', 'ENERO', 'ENOJO', 'ENTRA', 'ENTRE', 'ENVIO', 'EPOCA', 'ERAIS',
  'ERROR', 'ETAPA', 'ETNIA', 'EUROS', 'EVITA', 'EXIGE', 'EXIJA', 'EXITO',
  'EXTRA', 'FABLA', 'FALDA', 'FALLA', 'FALLO', 'FALSA', 'FALSO', 'FALTA',
  'FAMAS', 'FANGO', 'FARSA', 'FATAL', 'FAUNA', 'FAVOR', 'FECHA', 'FELIZ',
  'FERIA', 'FIBRA', 'FICHA', 'FIERA', 'FIERO', 'FIJAR', 'FILAS', 'FILMA',
  'FINAL', 'FINCA', 'FINOS', 'FIRMA', 'FIRME', 'FISCO', 'FLACO', 'FLAMA',
  'FLASH', 'FLOJA', 'FLOJO', 'FLORA', 'FLOTA', 'FLUJO', 'FOBIA', 'FOCOS',
  'FOLIO', 'FONDO', 'FORMA', 'FOROS', 'FOTOS', 'FRACO', 'FRASE', 'FRENO',
  'FRESA', 'FRIAS', 'FRITA', 'FRITO', 'FRUTA', 'FRUTO', 'FUEGO', 'FUERA',
  'FUGAS', 'FUMAR', 'FUNDA', 'FURIA', 'GAFAS', 'GALAN', 'GALLO', 'GAMAS',
  'GANAS', 'GANGA', 'GANAR', 'GASAS', 'GATAS', 'GATOS', 'GEMIR', 'GENES',
  'GENIO', 'GENTE', 'GESTO', 'GIRAR', 'GIROS', 'GLOBO', 'GOLFO', 'GOLPE',
  'GOMAS', 'GORDA', 'GORDO', 'GORRA', 'GOTEA', 'GOTAS', 'GOZAN', 'GOZAR',
  'GRACE', 'GRADO', 'GRAMA', 'GRANA', 'GRAVE', 'GRIPE', 'GRIPA', 'GRITO',
  'GRUPO', 'GRUTA', 'GUAPA', 'GUAPO', 'GUIAS', 'GUION', 'GUISO', 'GUSTA',
  'GUSTO', 'HABER', 'HABIA', 'HABLA', 'HACER', 'HACIA', 'HACEN', 'HAGAN',
  'HALLO', 'HARAS', 'HARTO', 'HASTA', 'HELAR', 'HERIR', 'HIELO', 'HIJOS',
  'HILAR', 'HIMNO', 'HIPER', 'HOBBY', 'HOGAR', 'HOJAS', 'HONDA', 'HONDO',
  'HONOR', 'HORAS', 'HOTEL', 'HOYAS', 'HOYOS', 'HUECO', 'HUELE', 'HUEVO',
  'HUIDA', 'HUMOR', 'HUMOS', 'HUYAN', 'IDEAS', 'IDEAL', 'IDOLO', 'IGUAL',
  'ILESO', 'IMITA', 'IMPAR', 'INDEX', 'INDIO', 'INFLA', 'INSTA', 'JAMON',
  'JAQUE', 'JARRA', 'JEFES', 'JESUS', 'JODER', 'JOVEN', 'JOYAS', 'JUEGA',
  'JUEGO', 'JUEZA', 'JUGAD', 'JUGAR', 'JUGOS', 'JUNIO', 'JUNTA', 'JUNTO',
  'JURAR', 'JUSTO', 'KARTS', 'KILOS', 'KIOSK', 'KOALA', 'LABIO', 'LABOR',
  'LACAR', 'LACRA', 'LADAR', 'LAICA', 'LAICO', 'LAMER', 'LANZA', 'LAPIZ',
  'LARGA', 'LARGO', 'LARVA', 'LASER', 'LATAS', 'LATIR', 'LAVAR', 'LAVAS',
  'LAZAN', 'LAZOS', 'LEGAL', 'LEJOS', 'LEMAS', 'LENTO', 'LEONA', 'LEPRA',
  'LETAL', 'LETRA', 'LEVAS', 'LEYES', 'LIBRO', 'LICOR', 'LIDIA', 'LIGAR',
  'LIGHT', 'LIJAS', 'LILAS', 'LIMAR', 'LINDO', 'LINEA', 'LISTA', 'LISTO',
  'LITRO', 'LLAGA', 'LLAMA', 'LLANA', 'LLANO', 'LLEGA', 'LLENA', 'LLENO',
  'LLEVA', 'LLORA', 'LLORO', 'LOBBY', 'LOBOS', 'LOCOS', 'LOCUS', 'LODOS',
  'LOGRA', 'LOGRO', 'LOMAS', 'LOMOS', 'LONAS', 'LOTES', 'LUCEN', 'LUCIR',
  'LUCHA', 'LUCHO', 'LUCIO', 'LUEGO', 'LUGAR', 'LUJAR', 'LUJOS', 'LUNAS',
  'LUNES', 'MACHO', 'MADRE', 'MAFIA', 'MAGOS', 'MALES', 'MALLA', 'MALOS',
  'MAMAS', 'MANCO', 'MANDO', 'MANGO', 'MANIA', 'MANOS', 'MANTA', 'MAPAS',
  'MARCA', 'MARCO', 'MAREA', 'MARES', 'MASAS', 'MATAS', 'MATIZ', 'MAYOR',
  'MAZOS', 'MECER', 'MEDAL', 'MEDIA', 'MEDIO', 'MEJOR', 'MENOS', 'MENTA',
  'MENTE', 'MENUS', 'MEROS', 'MESAS', 'MESES', 'METAL', 'METER', 'METRO',
  'MICRO', 'MIEDO', 'MINAS', 'MINAR', 'MIRAR', 'MIRAS', 'MISAS', 'MISIL',
  'MISMA', 'MISMO', 'MITAD', 'MITOS', 'MIXTA', 'MIXTO', 'MODAL', 'MODAS',
  'MODIO', 'MODOS', 'MOJAR', 'MOLDE', 'MOLER', 'MONJA', 'MONJE', 'MONTA',
  'MONTE', 'MORAL', 'MORAR', 'MORDE', 'MORIR', 'MOROS', 'MORSE', 'MOTOR',
  'MOTOS', 'MOVER', 'MOVIL', 'MOZOS', 'MUCHA', 'MUCHO', 'MUDAR', 'MUDOS',
  'MUECA', 'MUELA', 'MUERE', 'MUERO', 'MUJER', 'MULAS', 'MULTA', 'MUNDO',
  'MUROS', 'MUSAS', 'MUSGO', 'MUSLO', 'NACER', 'NACIO', 'NADAS', 'NADAR',
  'NADIE', 'NAFTA', 'NAIPE', 'NANAS', 'NARIZ', 'NASAL', 'NATAL', 'NATAS',
  'NAVES', 'NECIO', 'NEGAR', 'NEGRO', 'NENES', 'NETAS', 'NETOS', 'NICHO',
  'NIDOS', 'NIEGA', 'NIEVE', 'NIETA', 'NIETO', 'NINFA', 'NINAS', 'NINOS',
  'NIVEL', 'NOBEL', 'NOBLE', 'NOCHE', 'NODOS', 'NOMOS', 'NORMA', 'NORTE',
  'NOTAS', 'NOTAR', 'NOVIO', 'NUBES', 'NUBLA', 'NUCAS', 'NUDOS', 'NUERA',
  'NUEVA', 'NUEVO', 'NUEVE', 'NUNCA', 'OBESO', 'OBRAS', 'OBRAR', 'OBVIO',
  'OCASO', 'OCIOS', 'OCUPA', 'ODIAR', 'ODIOS', 'OESTE', 'OIDAS', 'OIDOS',
  'OJALA', 'OJEAR', 'OLIVA', 'OLLAS', 'OLMOS', 'ONDAS', 'OPACO', 'OPERA',
  'OPINA', 'OPTAR', 'ORDEN', 'OREJA', 'OSADO', 'OSEAS', 'OTROS', 'OVEJA',
  'PACTO', 'PADRE', 'PAGAS', 'PAGAR', 'PAGOS', 'PAJAS', 'PALOS', 'PANES',
  'PAPAL', 'PAPAS', 'PAPEL', 'PARAR', 'PARDO', 'PARED', 'PARIS', 'PARRA',
  'PARTE', 'PARTO', 'PASAR', 'PASAS', 'PASEO', 'PASOS', 'PASTA', 'PATAS',
  'PATIO', 'PATOS', 'PAUSA', 'PAVOR', 'PECAR', 'PECHO', 'PEDAL', 'PEDIR',
  'PEGAS', 'PEINE', 'PELAR', 'PENAS', 'PENAL', 'PENDE', 'PENES', 'PENSA',
  'PEONA', 'PEPAS', 'PERAS', 'PERDO', 'PEREZ', 'PERLA', 'PERRO', 'PESAR',
  'PESCA', 'PESOS', 'PESTE', 'PIANO', 'PICAR', 'PICOS', 'PIEDA', 'PIEZA',
  'PILAS', 'PINAR', 'PINOS', 'PINTA', 'PINTO', 'PIPAS', 'PISAR', 'PISOS',
  'PISTA', 'PITAR', 'PIZZA', 'PLACA', 'PLAGA', 'PLANA', 'PLANO', 'PLATA',
  'PLATO', 'PLAYA', 'PLAZA', 'PLAZO', 'PLENA', 'PLENO', 'PLUMA', 'POBLA',
  'POBRE', 'POCAS', 'POCOS', 'PODER', 'PODIA', 'POEMA', 'POETA', 'POLAR',
  'POLEA', 'POLEN', 'POLVO', 'PONER', 'PONGO', 'PORTA', 'PORTE', 'POSEE',
  'POSER', 'POSTE', 'POTAR', 'POTRA', 'POTRO', 'POZOS', 'PRADO', 'PRAVO',
  'PRESA', 'PRESO', 'PRIMA', 'PRIMO', 'PRIOR', 'PRISA', 'PROBO', 'PROLE',
  'PROSA', 'PUEDE', 'PULGA', 'PULIR', 'PULPO', 'PULSO', 'PUNAL', 'PUNOS',
  'PUNTA', 'PUNTO', 'PUPAS', 'PUROS', 'PUZLE', 'QUEDA', 'QUEJA', 'QUEMA',
  'QUESO', 'QUIEN', 'QUOTA', 'RABIA', 'RABOS', 'RACHA', 'RADAR', 'RADIO',
  'RAJAR', 'RAMAS', 'RAMPA', 'RAMOS', 'RANAS', 'RANGO', 'RAPAR', 'RAPAZ',
  'RARAS', 'RAROS', 'RASCO', 'RASGA', 'RASGO', 'RASOS', 'RASPA', 'RATAS',
  'RATON', 'RATOS', 'RAYAS', 'RAYOS', 'RAZAS', 'RAZON', 'REATA', 'REBAL',
  'REDES', 'REGIA', 'REGIO', 'REGIR', 'REINA', 'REJAS', 'RELOJ', 'REMAR',
  'REMOS', 'RENAL', 'RENCO', 'RENTA', 'RENOS', 'REPAS', 'REPOS', 'REPTO',
  'RESTO', 'RETAR', 'RETOS', 'REYES', 'REZAR', 'REZOS', 'RICLA', 'RIEGA',
  'RIEGO', 'RIELA', 'RIFAR', 'RIFLE', 'RIGIO', 'RIGOR', 'RIMAR', 'RIMAS',
  'RINON', 'RIOJA', 'RISAS', 'RISCO', 'RITMO', 'RITOS', 'RIVAL', 'RIZAR',
  'RIZOS', 'ROBAR', 'ROBOS', 'ROBOT', 'ROBRA', 'ROCAS', 'ROCIO', 'RODEA',
  'RODEO', 'ROGAR', 'ROJAS', 'ROJOS', 'ROLLO', 'ROMAN', 'ROMBO', 'ROMPE',
  'RONDA', 'RONDO', 'ROPAS', 'ROQUE', 'ROSAS', 'ROSCA', 'RUBIA', 'RUBIO',
  'RUBOR', 'RUBRO', 'RUEDA', 'RUEGO', 'RUIDO', 'RUINA', 'RUMBA', 'RUMBO',
  'RUMOR', 'RUNAS', 'RUPIA', 'RURAL', 'RUSAS', 'RUSOS', 'RUTAS', 'SABIA',
  'SABIO', 'SABLE', 'SABOR', 'SACAR', 'SACIA', 'SACOS', 'SAGAZ', 'SALAS',
  'SALDO', 'SALEN', 'SALGO', 'SALIR', 'SALMO', 'SALON', 'SALSA', 'SALTA',
  'SALTO', 'SALUD', 'SALVA', 'SALVO', 'SANAS', 'SANDE', 'SANOS', 'SANTA',
  'SANTO', 'SAPOS', 'SARNO', 'SARNA', 'SARTA', 'SAUCE', 'SAUNA', 'SAVIA',
  'SAXON', 'SECAS', 'SECAR', 'SECOS', 'SECTA', 'SEDAL', 'SEDAR', 'SEDES',
  'SEGAR', 'SEGUN', 'SELVA', 'SENAL', 'SENAS', 'SENOR', 'SERIA', 'SERIO',
  'SERVA', 'SERVO', 'SETAS', 'SIEGA', 'SIGLO', 'SIGNO', 'SIGUE', 'SILLA',
  'SILBO', 'SIMIO', 'SISMO', 'SITIO', 'SOBAR', 'SOBRE', 'SOCIA', 'SOCIO',
  'SODIO', 'SOFAS', 'SOGAS', 'SOLAR', 'SOLAS', 'SOLER', 'SOLOS', 'SOMOS',
  'SONAR', 'SOPAR', 'SOPLA', 'SOPOR', 'SORDA', 'SORDO', 'SORGO', 'SORNA',
  'SOROS', 'SORTE', 'SOTAS', 'SUAVE', 'SUBAS', 'SUBIR', 'SUCIA', 'SUCIO',
  'SUDOR', 'SUECO', 'SUELA', 'SUELE', 'SUELO', 'SUENA', 'SUERO', 'SUITE',
  'SUMAR', 'SUMOS', 'SUPER', 'SUPON', 'SURAR', 'SURCO', 'SURGE', 'SURJA',
  'SUTIL', 'SUYAS', 'SUYOS', 'TABLA', 'TACOS', 'TACTO', 'TALAR', 'TALAS',
  'TALON', 'TALLA', 'TALLO', 'TAMAL', 'TANGO', 'TANTA', 'TANTO', 'TAPAS',
  'TAPEN', 'TAPIA', 'TAPIR', 'TAPON', 'TAQUE', 'TARDA', 'TARDE', 'TAREA',
  'TAROT', 'TARRO', 'TARTA', 'TASAS', 'TASAR', 'TAXIS', 'TAZAS', 'TECLA',
  'TECHO', 'TEJAS', 'TEJEN', 'TEJER', 'TEJON', 'TELAS', 'TELER', 'TEMAS',
  'TEMER', 'TEMOR', 'TEMPO', 'TENAS', 'TENCA', 'TENER', 'TENGO', 'TENIA',
  'TENIS', 'TENSO', 'TENIR', 'TENUE', 'TERCO', 'TERNO', 'TERRA', 'TERSO',
  'TESIS', 'TESLA', 'TESTA', 'TEXTO', 'TIBIO', 'TIENE', 'TIERA', 'TIGRE',
  'TILAS', 'TILDE', 'TIMOS', 'TINAS', 'TINTA', 'TINTO', 'TIPOS', 'TIQUE',
  'TIRAR', 'TIRAS', 'TIROL', 'TIRON', 'TITAN', 'TOCAR', 'TODAS', 'TODOS',
  'TOGAS', 'TOLDO', 'TOMAR', 'TOMAS', 'TOMOS', 'TONAL', 'TONER', 'TONOS',
  'TONTA', 'TONTO', 'TOPAN', 'TOPAR', 'TOPES', 'TOQUE', 'TORAL', 'TORAX',
  'TOREO', 'TOROS', 'TORRE', 'TORSO', 'TORTA', 'TOTAL', 'TOTEM', 'TOURS',
  'TRABA', 'TRABO', 'TRACE', 'TRAER', 'TRAGO', 'TRAJE', 'TRAMA', 'TRAMO',
  'TRATO', 'TRAZO', 'TRECE', 'TRENA', 'TRENE', 'TRENS', 'TREPA', 'TRIGO',
  'TRINA', 'TRIPA', 'TRITE', 'TROJA', 'TRONA', 'TRONO', 'TROPA', 'TROTE',
  'TROVA', 'TROZA', 'TRUCO', 'TRUFA', 'TRUJE', 'TUBAL', 'TUBAS', 'TUBOS',
  'TUMBA', 'TUMOR', 'TUNAS', 'TUNEL', 'TURBA', 'TURBO', 'TURCA', 'TURCO',
  'TURNO', 'TUTOR', 'TUYAS', 'TUYOS', 'UBICA', 'ULCER', 'ULTRA', 'UNICA',
  'UNICO', 'UNIDO', 'UNION', 'UNITA', 'UNTAR', 'UNTOS', 'URANO', 'URBIS',
  'URDIR', 'URGIR', 'URNAS', 'USADA', 'USADO', 'USARA', 'USURA', 'UTERO',
  'UVULA', 'VACAS', 'VACIA', 'VACIO', 'VAGAR', 'VAGON', 'VALER', 'VALES',
  'VALGA', 'VALLA', 'VALLE', 'VALOR', 'VALSA', 'VAPOR', 'VARAS', 'VARIO',
  'VARON', 'VASAR', 'VASOS', 'VAYAN', 'VECES', 'VECIN', 'VEDAS', 'VEGAS',
  'VEJAN', 'VEJAR', 'VEJEZ', 'VELAS', 'VELAR', 'VELOZ', 'VEMOS', 'VENAS',
  'VENCE', 'VENDA', 'VENDE', 'VENIR', 'VENTA', 'VENUS', 'VERAS', 'VERBO',
  'VERDE', 'VERGA', 'VERIA', 'VERSO', 'VETAN', 'VETAR', 'VETAS', 'VEXAR',
  'VIAJE', 'VIBRA', 'VICIO', 'VIDAS', 'VIDEO', 'VIEJA', 'VIEJO', 'VIENE',
  'VIGAS', 'VIGOR', 'VILAS', 'VILES', 'VILLA', 'VINCA', 'VINCO', 'VINOS',
  'VIOLA', 'VIRAL', 'VIRUS', 'VISAR', 'VISAS', 'VISIR', 'VISON', 'VISOR',
  'VISTA', 'VISTO', 'VITAL', 'VIUDA', 'VIUDO', 'VIVAN', 'VIVAS', 'VIVAZ',
  'VIVIR', 'VIVOS', 'VOCAL', 'VOCES', 'VODKA', 'VOLAR', 'VOLEA', 'VOLTA',
  'VOLTS', 'VORAZ', 'VOTAR', 'VOTOS', 'VULGO', 'YACEN', 'YACER', 'YATES',
  'YEDRA', 'YEGUA', 'YEMAS', 'YENDO', 'YERNO', 'YERRO', 'YESOS', 'YOGUR',
  'YOYOS', 'ZAFAR', 'ZAGAS', 'ZANJA', 'ZARES', 'ZARPA', 'ZARZA', 'ZONAS',
  'ZONDA', 'ZORRO', 'ZUECO', 'ZUMBA', 'ZUMOS', 'ZURDA', 'ZURDO', 'ZURRA',
  // ===== 6-LETTER ENGLISH WORDS =====
  'ACCEPT', 'ACCESS', 'ACROSS', 'ACTION', 'ACTIVE', 'ACTUAL', 'ADVICE',
  'ADVISE', 'AFFAIR', 'AFFECT', 'AFFORD', 'AFRAID', 'AGENCY', 'AGENDA',
  'ALMOST', 'ALWAYS', 'AMOUNT', 'ANIMAL', 'ANNUAL', 'ANSWER', 'ANYONE',
  'ANYWAY', 'APPEAL', 'APPEAR', 'AROUND', 'ARRIVE', 'ARTIST', 'ASPECT',
  'ASSESS', 'ASSIST', 'ASSUME', 'ATTACK', 'ATTEND', 'AUGUST', 'AUTHOR',
  'AVENUE', 'BACKED', 'BACKUP', 'BANNER', 'BARELY', 'BARREL', 'BASKET',
  'BATTLE', 'BEAUTY', 'BECAME', 'BECOME', 'BEFORE', 'BEHALF', 'BEHAVE',
  'BEHIND', 'BEINGS', 'BELIEF', 'BELONG', 'BERLIN', 'BESIDE', 'BETTER',
  'BEYOND', 'BISHOP', 'BLACKS', 'BOARDS', 'BODIES', 'BORDER', 'BORING',
  'BORROW', 'BOTTLE', 'BOTTOM', 'BOUGHT', 'BOUNCE', 'BOUNDS',
  'BOXING', 'BRANCH', 'BRANDS', 'BREACH', 'BREAKS', 'BREAST', 'BREATH',
  'BRIDGE', 'BRIGHT', 'BRINGS', 'BROKEN', 'BROKER', 'BRONZE', 'BROWSE',
  'BRUTAL', 'BUDGET', 'BUFFER', 'BURDEN', 'BUREAU', 'BURIED', 'BURNER',
  'BUTTER', 'BUTTON', 'BUYERS', 'BUYING', 'CALLED', 'CALLER', 'CAMERA',
  'CAMPUS', 'CANADA', 'CANCER', 'CANVAS', 'CAPITA', 'CARBON', 'CAREER',
  'CARING', 'CASINO', 'CASTLE', 'CASUAL', 'CATTLE', 'CAUGHT', 'CAUSED',
  'CAUSES', 'CEMENT', 'CENTER', 'CENTRE', 'CHAIRS', 'CHANCE', 'CHANGE',
  'CHAPEL', 'CHARGE', 'CHARTS', 'CHEESE', 'CHIEFS', 'CHOICE', 'CHOOSE',
  'CHOSEN', 'CHRIST', 'CHROME', 'CHURCH', 'CIRCLE', 'CIRCUS', 'CITIES',
  'CLAIMS', 'CLAIRE', 'CLAUSE', 'CLIENT', 'CLIMAX', 'CLINIC', 'CLOSED',
  'CLOSER', 'CLOUDS', 'CLUTCH', 'COBALT', 'CODING', 'COFFEE', 'COLLAR',
  'COLONY', 'COLORS', 'COLOUR', 'COLUMN', 'COMBAT', 'COMEDY', 'COMING',
  'COMMIT', 'COMMON', 'COMPLY', 'CONVEY', 'COOKED', 'COOLER', 'COOPER',
  'COPPER', 'COPIES', 'CORNER', 'CORPUS', 'COSTLY', 'COTTON', 'COUNTS',
  'COUNTY', 'COUPLE', 'COUPON', 'COURSE', 'COURTS', 'COVERS', 'CREATE',
  'CREDIT', 'CREEPY', 'CRIMES', 'CRISIS', 'CRITIC', 'CROWDS', 'CRUISE',
  'CUSTOM', 'CYCLES', 'DAMAGE', 'DANCER', 'DANGER', 'DANISH', 'DEALER',
  'DEBATE', 'DEBRIS', 'DECADE', 'DECENT', 'DECIDE', 'DECREE', 'DEEMED',
  'DEEPLY', 'DEFEAT', 'DEFEND', 'DEFINE', 'DEGREE', 'DELAYS', 'DELETE',
  'DEMAND', 'DENIAL', 'DENIED', 'DENTAL', 'DEPEND', 'DEPLOY', 'DEPUTY',
  'DERIVE', 'DESERT', 'DESIGN', 'DESIRE', 'DETAIL', 'DETECT', 'DEVICE',
  'DIALOG', 'DIFFER', 'DIGEST', 'DINING', 'DINNER', 'DIRECT', 'DISNEY',
  'DIVIDE', 'DOCTOR', 'DOLLAR', 'DOMAIN', 'DONATE', 'DOUBLE', 'DOZENS',
  'DRAWER', 'DREAMS', 'DRINKS', 'DRIVEN', 'DRIVER', 'DRIVES', 'DRYING',
  'DUBLIN', 'DURING', 'DUTIES', 'EASIER', 'EASILY', 'EATING', 'ECHOES',
  'EDITOR', 'EFFECT', 'EFFORT', 'EIGHTH', 'EITHER', 'ELDEST', 'ELEVEN',
  'EMBRYO', 'EMERGE', 'EMPIRE', 'EMPLOY', 'ENABLE', 'ENDING', 'ENERGY',
  'ENGAGE', 'ENGINE', 'ENJOYS', 'ENOUGH', 'ENSURE', 'ENTERS', 'ENTIRE',
  'ENTITY', 'ENZYME', 'EQUITY', 'EROTIC', 'ERRORS', 'ESCAPE', 'ESSAYS',
  'ESTATE', 'ETHICS', 'ETHNIC', 'EUROPE', 'EVENTS', 'EXCEPT', 'EXCESS',
  'EXCUSE', 'EXISTS', 'EXPAND', 'EXPECT', 'EXPERT', 'EXPIRE', 'EXPORT',
  'EXTEND', 'EXTENT', 'FABRIC', 'FACIAL', 'FACING', 'FACTOR', 'FAILED',
  'FAIRLY', 'FALLEN', 'FAMILY', 'FAMOUS', 'FARMER', 'FASTER', 'FATHER',
  'FAVOUR', 'FEARED', 'FELLOW', 'FEMALE', 'FIELDS', 'FIERCE', 'FIGURE',
  'FILING', 'FILTER', 'FINDER', 'FINGER', 'FINISH', 'FISCAL', 'FISHER',
  'FITTED', 'FITTER', 'FIXING', 'FLAMES', 'FLAVOR', 'FLIGHT', 'FLOODS',
  'FLOORS', 'FLOWER', 'FLYING', 'FOLDER', 'FOLLOW', 'FORCED', 'FORCES',
  'FOREST', 'FORGET', 'FORGOT', 'FORMAL', 'FORMAT', 'FORMED', 'FORMER',
  'FORUMS', 'FOSTER', 'FOUGHT', 'FOURTH', 'FRANCE', 'FRENCH', 'FRIEND',
  'FROZEN', 'FRUITS', 'FUNDED', 'FUSION', 'FUTURE', 'GALLON',
  'GAMBLE', 'GAMING', 'GARAGE', 'GARDEN', 'GATHER', 'GEARED', 'GENDER',
  'GENIUS', 'GENTLE', 'GENTLY', 'GERMAN', 'GIANTS', 'GIFTED', 'GIVING',
  'GLOBAL', 'GLOSSY', 'GOLDEN', 'GOOGLE', 'GOTTEN', 'GOVERN', 'GRADES',
  'GRAINS', 'GRANTS', 'GRAVEL', 'GREECE', 'GREENS', 'GROOVE', 'GROUND',
  'GROUPS', 'GROWTH', 'GUARDS', 'GUIDED', 'GUIDES', 'GUITAR', 'GUILTY',
  'HABITS', 'HAMMER', 'HANDED', 'HANDLE', 'HAPPEN', 'HARBOR',
  'HARDLY', 'HARRIS', 'HAWAII', 'HAZARD', 'HEADED', 'HEADER',
  'HEALTH', 'HEARTS', 'HEATED', 'HEATER', 'HEAVEN', 'HEBREW', 'HEIGHT',
  'HELPED', 'HELPER', 'HEREBY', 'HEROES', 'HIDDEN', 'HIGHER', 'HIGHLY',
  'HOLDER', 'HOLLOW', 'HOMAGE', 'HONEST', 'HONORS', 'HOPING', 'HORROR',
  'HORSES', 'HOSTED', 'HOTELS', 'HOURLY', 'HOUSED', 'HOUSES', 'HUMANS',
  'HUMBLE', 'HUNGRY', 'HUNTER', 'HYBRID', 'IGNORE', 'IMAGES', 'IMMUNE',
  'IMPACT', 'IMPORT', 'IMPOSE', 'INCHES', 'INCOME', 'INDEED', 'INDIAN',
  'INDOOR', 'INFORM', 'INJURY', 'INSECT', 'INSERT', 'INSIDE', 'INSIST',
  'INSURE', 'INTAKE', 'INTACT', 'INTENT', 'INTERN', 'INVEST', 'INVITE',
  'INVOKE', 'INWARD', 'ISLAND', 'ISSUED', 'ISSUES', 'ITSELF', 'JACKET',
  'JAILED', 'JERSEY', 'JOINED', 'JOINTS', 'JOSEPH', 'JUNGLE', 'JUNIOR',
  'KEEPER', 'KERNEL', 'KICKED', 'KILLED', 'KILLER', 'KINDLY', 'KNIGHT',
  'LABELS', 'LABOUR', 'LADIES', 'LANDED', 'LAPTOP', 'LARGER', 'LATEST',
  'LATINS', 'LATTER', 'LAUNCH', 'LAWYER', 'LAYERS', 'LAYOUT', 'LEADER',
  'LEAGUE', 'LEANED', 'LEARNS', 'LEASED', 'LEAVES', 'LEGACY', 'LEGEND',
  'LENDER', 'LENGTH', 'LESSON', 'LETTER', 'LEVELS', 'LIABLE', 'LIGHTS',
  'LIKELY', 'LIMITS', 'LINEAR', 'LINEUP', 'LINKED', 'LIQUID', 'LISTED',
  'LISTEN', 'LITTLE', 'LIVELY', 'LIVING', 'LOADED', 'LOCATE', 'LOCKED',
  'LOGGED', 'LONDON', 'LONELY', 'LONGER', 'LOOKED', 'LOSING', 'LOSSES',
  'LOUNGE', 'LOVELY', 'LOVERS', 'LOWEST', 'LUXURY', 'LYRICS', 'MADRID',
  'MAINLY', 'MAKERS', 'MAKEUP', 'MAKING', 'MANAGE', 'MANILA', 'MANNER',
  'MANUAL', 'MARBLE', 'MARGIN', 'MARINE', 'MARKED', 'MARKER', 'MARKET',
  'MARTIN', 'MASTER', 'MATRIX', 'MATTER', 'MATURE', 'MEDIUM', 'MEMBER',
  'MEMORY', 'MENTAL', 'MENTOR', 'MERELY', 'MERGER', 'METHOD', 'MEXICO',
  'MIDDLE', 'MIGHTY', 'MILLER', 'MINING', 'MINUTE', 'MIRROR', 'MISERY',
  'MISSED', 'MISTER', 'MOBILE', 'MODELS', 'MODERN', 'MODEST', 'MODULE',
  'MOMENT', 'MONKEY', 'MONTHS', 'MORTAL', 'MOSTLY', 'MOTHER', 'MOTION',
  'MOTIVE', 'MOTORS', 'MOVING', 'MURDER', 'MURPHY', 'MUSCLE', 'MUSEUM',
  'MUTUAL', 'MYSELF', 'NAMELY', 'NARROW', 'NATION', 'NATIVE', 'NATURE',
  'NEARBY', 'NEARLY', 'NEEDED', 'NEEDLE', 'NELSON', 'NEPHEW', 'NERVES',
  'NEURAL', 'NICELY', 'NIGHTS', 'NINETY', 'NOBODY', 'NORDIC', 'NORMAL',
  'NOTICE', 'NOTION', 'NOVELS', 'NUMBER', 'OBJECT', 'OBTAIN', 'OCCUPY',
  'OCCURS', 'OCEANS', 'OFFERS', 'OFFICE', 'OFFSET', 'OLDEST', 'ONLINE',
  'OPENED', 'OPENER', 'OPENLY', 'OPTICS', 'OPTION', 'ORACLE', 'ORANGE',
  'ORDERS', 'ORGANS', 'ORIGIN', 'OTHERS', 'OUTFIT', 'OUTLET', 'OUTPUT',
  'OWNERS', 'OXYGEN', 'PACKED', 'PACKET', 'PALACE', 'PANELS', 'PAPERS',
  'PARADE', 'PARENT', 'PARISH', 'PARKER', 'PARTLY', 'PASSED', 'PASSES',
  'PASTOR', 'PATENT', 'PATROL', 'PATRON', 'PAUSED', 'PAYING',
  'PENCIL', 'PEOPLE', 'PEPPER', 'PERIOD', 'PERMIT', 'PERSON', 'PHRASE',
  'PICKED', 'PICKUP', 'PICNIC', 'PIECES', 'PILLOW', 'PIRATE', 'PISTOL',
  'PLACED', 'PLACES', 'PLAINS', 'PLANES', 'PLANET', 'PLANTS', 'PLASMA',
  'PLATES', 'PLAYED', 'PLAYER', 'PLEASE', 'PLENTY', 'PLUGIN', 'PLUNGE',
  'POCKET', 'POETRY', 'POINTS', 'POISON', 'POLICE', 'POLICY', 'POLISH',
  'POLITE', 'POORLY', 'PORTAL', 'POSTER', 'POTATO', 'POTTER', 'POUNDS',
  'POWDER', 'POWERS', 'PRAISE', 'PRAYER', 'PREFER', 'PRETTY', 'PRICES',
  'PRIEST', 'PRINCE', 'PRINTS', 'PRISON', 'PRIZES', 'PROFIT', 'PROMPT',
  'PROPER', 'PROVEN', 'PROVES', 'PUBLIC', 'PULLED', 'PUNISH', 'PURELY',
  'PURPLE', 'PURSUE', 'PUSHED', 'PUZZLE', 'PYTHON', 'QUARRY', 'QUEENS',
  'QUOTES', 'RABBIT', 'RACIAL', 'RACING', 'RACIST', 'RADIAL', 'RADIUS',
  'RAISED', 'RAISES', 'RANDOM', 'RANGER', 'RANKED', 'RARELY', 'RATHER',
  'RATING', 'RATIOS', 'READER', 'REALLY', 'REALMS', 'REASON', 'RECALL',
  'RECENT', 'RECIPE', 'RECORD', 'REDUCE', 'REFORM', 'REFUSE', 'REGARD',
  'REGIME', 'REGION', 'REJECT', 'RELATE', 'RELIEF', 'REMAIN',
  'REMARK', 'REMEDY', 'REMIND', 'REMOTE', 'REMOVE', 'RENDER', 'RENTAL',
  'REPAIR', 'REPEAT', 'REPLAY', 'REPORT', 'RESCUE', 'RESIGN', 'RESORT',
  'RESULT', 'RESUME', 'RETAIL', 'RETAIN', 'RETIRE', 'RETURN', 'REVEAL',
  'REVIEW', 'REVOLT', 'REWARD', 'RHYTHM', 'RIBBON', 'RICHES', 'RIDING',
  'RIGHTS', 'RISING', 'RIVERS', 'ROBUST', 'ROCKET', 'ROLLED', 'ROMANS',
  'ROOTED', 'ROSTER', 'ROUTES', 'ROWING', 'RUBBER', 'RUBRIC', 'RULING',
  'RUNNER', 'RUSHED', 'RUSSIA', 'SACRED', 'SADDLE', 'SAFARI',
  'SAFELY', 'SAFETY', 'SAINTS', 'SALARY', 'SALMON', 'SAMPLE', 'SAVING',
  'SAYING', 'SCALED', 'SCALES', 'SCENES', 'SCHEME', 'SCHOOL', 'SCORED',
  'SCORES', 'SCOUTS', 'SCREEN', 'SCRIPT', 'SCROLL', 'SEARCH', 'SEASON',
  'SECOND', 'SECRET', 'SECTOR', 'SECURE', 'SEEING', 'SEEMED', 'SELECT',
  'SELLER', 'SENATE', 'SENIOR', 'SENSOR', 'SERIES', 'SERVED', 'SERVER',
  'SERVES', 'SETTLE', 'SEVERE', 'SEXUAL', 'SHADOW', 'SHAPED', 'SHAPES',
  'SHARED', 'SHARES', 'SHELLS', 'SHIELD', 'SHIFTS', 'SHIRTS', 'SHOOTS',
  'SHORTS', 'SHOULD', 'SHOWED', 'SHOWER', 'SHRINK', 'SIERRA', 'SIGNAL',
  'SIGNED', 'SILENT', 'SILVER', 'SIMPLE', 'SIMPLY', 'SINGER', 'SINGLE',
  'SISTER', 'SKETCH', 'SKILLS', 'SLEEVE', 'SLIDER', 'SLIGHT', 'SLOWLY',
  'SMELLS', 'SMOOTH', 'SNACKS', 'SOCCER', 'SOCIAL', 'SOCKET', 'SODIUM',
  'SOFTER', 'SOLELY', 'SOLVED', 'SOLVER', 'SOUGHT', 'SOUNDS', 'SOURCE',
  'SOVIET', 'SPEAKS', 'SPEECH', 'SPHERE', 'SPIDER', 'SPIRIT', 'SPLASH',
  'SPOKEN', 'SPORTS', 'SPREAD', 'SPRING', 'SQUARE', 'STABLE', 'STAGES',
  'STAIRS', 'STAKES', 'STANCE', 'STANDS', 'STARTS', 'STATED', 'STATES',
  'STATUE', 'STATUS', 'STAYED', 'STEADY', 'STEREO', 'STICKY', 'STOCKS',
  'STOLEN', 'STONES', 'STORED', 'STORES', 'STRAIN', 'STRAND', 'STREAM',
  'STREET', 'STRESS', 'STRICT', 'STRIKE', 'STRING', 'STRIPS', 'STROKE',
  'STRONG', 'STRUCK', 'STUDIO', 'STUPID', 'STYLES', 'SUBMIT', 'SUBTLE',
  'SUBURB', 'SUFFER', 'SUGARY', 'SUITED', 'SUITES', 'SUMMER', 'SUMMIT',
  'SUNDAY', 'SUNSET', 'SUPERB', 'SUPPLY', 'SURELY', 'SURVEY', 'SWITCH',
  'SYMBOL', 'SYNTAX', 'SYSTEM', 'TABLES', 'TABLET', 'TACKLE', 'TACTIC',
  'TAKING', 'TALENT', 'TALKED', 'TALLER', 'TARGET', 'TAUGHT', 'TAYLOR',
  'TEMPLE', 'TENANT', 'TENDER', 'TENNIS', 'TENURE', 'TERROR', 'TESTED',
  'THANKS', 'THAMES', 'THEIRS', 'THEMES', 'THEORY', 'THIRTY', 'THOMAS',
  'THOUGH', 'THREAD', 'THREAT', 'THRILL', 'THRONE', 'THROWN', 'THRUST',
  'THUMBS', 'TICKET', 'TIMBER', 'TIMING', 'TISSUE', 'TITLES', 'TOILET',
  'TOMATO', 'TONGUE', 'TOPICS', 'TOPPED', 'TORQUE', 'TOWARD', 'TOWERS',
  'TOYOTA', 'TRACED', 'TRACKS', 'TRADER', 'TRADES', 'TRAILS', 'TRAINS',
  'TRAITS', 'TRAUMA', 'TRAVEL', 'TREATY', 'TRENDS', 'TRIALS', 'TRIBAL',
  'TRIBES', 'TRICKS', 'TRIPLE', 'TROOPS', 'TROPHY', 'TRUCKS', 'TRUSTS',
  'TRUSTY', 'TRYING', 'TUCKED', 'TUNNEL', 'TURKEY', 'TURNED', 'TURTLE',
  'TWELVE', 'TWENTY', 'TYPING', 'ULTIMA', 'UNABLE', 'UNBORN', 'UNIQUE',
  'UNITED', 'UNLESS', 'UNLIKE', 'UNLOCK', 'UNSAFE', 'UPDATE', 'UPLOAD',
  'UPWARD', 'URGENT', 'USABLE', 'USEFUL', 'VACUUM', 'VALLEY', 'VALUED',
  'VALUES', 'VARIED', 'VARIES', 'VASTLY', 'VECTOR', 'VENDOR', 'VENICE',
  'VENUES', 'VERBAL', 'VERIFY', 'VERSUS', 'VESSEL', 'VIABLE', 'VICTIM',
  'VIDEOS', 'VIEWED', 'VIEWER', 'VIKING', 'VIRGIN', 'VIRTUE', 'VISION',
  'VISITS', 'VISUAL', 'VOICES', 'VOLUME', 'VOTERS', 'VOTING', 'WAITED',
  'WAITER', 'WALKER', 'WALKED', 'WALLET', 'WANDER', 'WANTED', 'WARMLY',
  'WARMTH', 'WARNED', 'WARREN', 'WASHED', 'WATERS', 'WEAPON', 'WEEKLY',
  'WEIGHT', 'WHEELS', 'WIDELY', 'WIDGET', 'WILLED', 'WILLIS', 'WILSON',
  'WINDOW', 'WINNER', 'WINTER', 'WIRING', 'WISDOM', 'WISELY', 'WISHED',
  'WISHES', 'WITHIN', 'WIZARD', 'WOLVES', 'WONDER', 'WOODEN', 'WORKED',
  'WORKER', 'WORLDS', 'WORTHY', 'WOUNDS', 'WRITER', 'WRITES', 'YELLOW',
  'YIELDS', 'ZOMBIE', 'ZONING',
  // ===== 6-LETTER SPANISH WORDS =====
  'ABARCA', 'ABIERTO', 'ABORTO', 'ABRAZO', 'ABUELO',
  'ABUELA', 'ACCESO', 'ACEITE', 'ACERCA', 'ACTIVA', 'ACTIVO', 'ACTRIZ',
  'ACUDIR', 'ADEMAS', 'ADONDE', 'ADULTO', 'AGENDA', 'AGOSTO',
  'AHORRO', 'AJENAS', 'AJENOS', 'ALARMA', 'ALEGRE', 'ALGUNA',
  'ALGUNO', 'ALIADO', 'ALISTA', 'ALTURA', 'AMABLE', 'AMANTE',
  'AMBITO', 'AMENAS', 'AMENOS', 'AMIGOS', 'AMPLIA', 'AMPLIO',
  'ANIMAL', 'ANIMOS', 'APENAS', 'APOYAN', 'APOYAR',
  'ARRIBA', 'ASISTE', 'ASUNTO', 'ATAQUE',
  'AUNQUE', 'AURORA',  'AVANCE',
  'AYUDAR', 'AZULES', 'BAILAR', 'BARCOS', 'BARRIO',
  'BASADO', 'BASURA', 'BEBIDA', 'BLANCA', 'BLANCO',
  'BOCINA', 'BOLETO', 'BONITA', 'BONITO', 'BOSQUE', 'BRASIL',
  'BROMAS', 'BUENOS', 'BUSCAR', 'CABEZA', 'CADENA', 'CADERA', 'CALIDO',
  'CALLAR', 'CAMBIO', 'CAMINA', 'CAMINO', 'CAMPOS', 'CANCEL', 'CANTAR',
  'CANTON', 'CAPTAR', 'CARCEL', 'CARGAR', 'CARNES', 'CARROS', 'CARTAS',
  'CASADO', 'CASERA', 'CASERO', 'CASINO', 'CAUSAS', 'CAUSAR',
  'CENTRO', 'CERCAS', 'CIELOS', 'CIERTO', 'CIFRAS', 'CIUDAD', 'CIVICA',
  'CIVICO', 'CLASES', 'CLAVES', 'CLIMAS', 'COBRAR', 'COCINA', 'CODIGO',
  'COLOCA', 'COLONO', 'COMIDA', 'COMITE', 'COMODO',
  'COMPRA', 'CONTAR', 'CONTRA', 'CORRER', 'CORTES', 'CORTOS', 'COSTAS',
  'CREATE', 'CRECER', 'CRIMEN', 'CRISIS', 'CUANDO', 'CUBANA',
  'CUBANO', 'CUENTA', 'CUERDA', 'CUERPO', 'CUIDAN', 'CUIDAR', 'CULPAR',
  'CUMBRE', 'CUMPLE', 'CURSOS', 'DANZAR', 'DEBAJO', 'DEBATE',
  'DEBIDO', 'DECIDE', 'DEDICA', 'DEJADO',
  'DELITO', 'DEMORA', 'DENTRO', 'DESEAR', 'DESEOS',
  'DEUDAS', 'DIARIA', 'DIARIO', 'DICHOS',
  'DIENTE', 'DINERO', 'DIOSES', 'DISCOS',
  'DISENO', 'DOCENA', 'DOCTOR',
  'DORMIR', 'DOTADO', 'DUENAS',
  'DUENOS', 'DULCES', 'DUREZA', 'EDITOR', 'EFECTO',
  'EMPATE', 'ENCARA',
  'ENCIMA', 'ENORME', 'ENSAYO', 'ENTERA', 'ENTERO',
  'ENTRAR', 'EQUIPO', 'ESCALA', 'ESCENA',
  'ESCUDO', 'ESPADA',
  'ESPANA', 'ESPERA', 'ESPOSA', 'ESPOSO',
  'ESTABA', 'ESTADO', 'ESTILO', 'ETAPAS',
  'EVENTO', 'EVITAR', 'EXACTA', 'EXACTO', 'EXAMEN', 'EXCESO', 'EXIGIR',
  'EXISTE', 'EXITOS', 'FACTOR', 'FALLAR', 'FALSOS',
  'FALTAS', 'FAMOSA', 'FAMOSO', 'FECHAS',
  'FIGURA', 'FILMAR',
  'FISCAL', 'FISICA', 'FISICO', 'FLECHA', 'FLORES', 'FONDOS',
  'FORMAS', 'FORMAR', 'FORZAR', 'FRAUDE', 'FRENTE', 'FRESCA', 'FRESCO',
  'FRUTOS', 'FUENTE', 'FUERAS', 'FUERTE', 'FUERZA',
  'FUTBOL', 'FUTURO', 'GANADO',
  'GASTOS', 'GENERO', 'GENIAL', 'GESTOS', 'GLOBAL',
  'GLORIA', 'GOLPEA', 'GOLPES', 'GORDAS', 'GORDOS', 'GRACIA', 'GRADOS',
  'GRANDE', 'GRANJA', 'GRANOS', 'GRATIS', 'GRAVAR', 'GRIEGO', 'GRIEGA',
  'GRIETA', 'GRUPOS', 'GUARDA', 'GUERRA', 'HABLAR',
  'HAMBRE', 'HARINA', 'HERIDA', 'HERIDO', 'HEROES',
  'HIERBA', 'HIERRO', 'HOMBRE', 'HONRAR', 'HUELGA', 'HUMANA', 'HUMANO',
  'HUMEDA', 'HUMEDO', 'IDIOMA', 'IMAGEN', 'IMITAR',
  'INDICE', 'INGLES', 'INICIO',
  'JARDIN', 'JUEGOS', 'JUICIO', 'JUNTAS', 'JUNTOS', 'JURADO',
  'JUSTOS', 'LABORA', 'LADRON', 'LAGUNA', 'LANZAR', 'LARGOS', 'LATINA',
  'LATINO', 'LECTOR', 'LENGUA', 'LETRAS', 'LIBERA',
  'LIBRAR', 'LIBRES', 'LIBROS', 'LIGERA', 'LIGERO', 'LIMITA',
  'LIMPIO', 'LINEAS', 'LISTAS', 'LISTOS', 'LLAMAN', 'LLAMAR', 'LLEGAN',
  'LLEGAR', 'LLENAR', 'LLEVAR', 'LLORAR', 'LLOVER', 'LLUVIA', 'LOCURA',
  'LOGICA', 'LOGRAR', 'LUCHAS', 'LUJOSO', 'MADERA',
  'MADRES', 'MAGICA', 'MAGICO', 'MANANA', 'MANDAN', 'MANDAR', 'MANERA',
  'MANGAS', 'MANOJO', 'MANUAL', 'MARCAR', 'MARCOS',
  'MARGEN', 'MARINO', 'MARTES', 'MASIVA', 'MASIVO',
  'MEDIDA', 'MEDIOS', 'MEJORA',
  'MENTAL', 'MERECE', 'METODO', 'METROS',
  'MEZCLA', 'MIEDOS', 'MILLON', 'MINIMA', 'MINIMO',
  'MINUTO', 'MIRADA', 'MIRABA', 'MISION', 'MODELO',
  'MONEDA', 'MONTES', 'MORENA', 'MORENO',
  'MOTIVA', 'MOTIVO', 'MUCHAS', 'MUCHOS', 'MUERTE',
  'MULTAS', 'MUSEOS', 'MUSICA',
  'NACION', 'NAVEGA', 'NERVIO', 'NINGUN',
  'NOCHES', 'NOMBRE', 'NORMAL', 'NORMAS', 'NOVELA', 'NUBLAR', 'NUEVAS', 'NUEVOS', 'NUMERO', 'OBJETO',
  'OBLIGA', 'OCEANO', 'OCUPAR', 'OFENDE',
  'OFICIN', 'OFRECE', 'OPERAN', 'OPCION', 'OPERAR', 'OPINAR',
  'ORGANO', 'ORIGEN', 'OSCURA', 'OSCURO', 'OTORGA', 'PADECE',
  'PADRES', 'PALOMA',
  'PARADA', 'PARECE', 'PAREJA',
  'PARQUE', 'PARTES', 'PASADO', 'PASAJE', 'PATRON',
  'PAUSAR', 'PECADO', 'PEDIDO', 'PELEAN', 'PELEAR',
  'PELOTA', 'PENSAR', 'PERDER',
  'PERDON', 'PIEDRA', 'PIERNA',
  'PILOTO', 'PINTAR', 'PINTOR', 'PIRATA', 'PLACER', 'PLANES', 'PLANOS',
  'PLANTA', 'PLATAS', 'PLATOS', 'PLAYAS', 'PLAZAS', 'PLENOS', 'PLUMAS',
  'POBLAR', 'POBRES', 'POEMAS', 'POLLOS',
  'PORTAL', 'PORTAR', 'POSEER', 'POSTER',
  'PRECIO', 'PREDIO', 'PRENSA',
  'PREVIO', 'PRIMER',
  'PROBAR', 'PRONTO', 'PROPIO',
  'PRUEBA', 'PUEBLO', 'PUERTA',
  'PUERTO', 'PULGAR', 'PUNTOS', 'QUEDAR', 'QUEMAR', 'QUERER',
  'QUITAR', 'RACIAL', 'RADICA', 'RADIOS', 'RANCHO', 'RAPIDA', 'RAPIDO',
  'RASGOS', 'REGALO', 'REGION',
  'REGLAS', 'RELATA', 'RELATO',
  'REMOTA', 'REMOTO', 'RENDIR', 'RENTAR', 'REPARA', 'REPITE',
  'RESTOS', 'RESUME', 'RETIRO',
  'REUNIR', 'REVELA', 'RIGIDO',
  'RITUAL', 'RODEAR', 'ROMPER', 'ROSTRO',
  'RUEDAS', 'RUIDOS', 'SABORY',
  'SALUDO', 'SALVAR', 'SANGRE', 'SANTAS', 'SANTOS',
  'SECTOR', 'SEGURA', 'SEGURO', 'SEGUIR', 'SEMANA', 'SENADO', 'SENIOR',
  'SEPARA', 'SERIAL', 'SERIES', 'SERVIR',
  'SEVERA', 'SEVERO', 'SIERRA', 'SIGNOS',
  'SIMPLE', 'SIRVEN', 'SITIOS', 'SOBRAS', 'SOCIAL',
  'SOCIOS', 'SOLIDA', 'SOLIDO', 'SOLTAR', 'SOMBRA',
  'SONIDO', 'SOPLAR', 'SORTEO', 'SUAVES', 'SUBIDA',
  'SUCEDE', 'SUCESO', 'SUFREN', 'SUFRIR', 'SUJETO',
  'SUPONE', 'SURGEN', 'SURGIR',
  'TAMBOR', 'TANQUE', 'TARDES', 'TARIFA', 'TEATRO', 'TEJIDO',
  'TEMPLO', 'TENDER', 'TERCER', 'TERMIN',
  'TEXTOS', 'TIEMPO', 'TIENDA', 'TIERRA', 'TIENEN', 'TIRADA',
  'TITULO', 'TOLERA', 'TONTOS', 'TOQUES', 'TORNEO',
  'TORRES', 'TRAMPA', 'TRATAR', 'TRATOS', 'TRAZAR', 'TRENES', 'TRIBUS',
  'TRISTE', 'TRONAR', 'TROPAS', 'TUMBAR',
  'TURNO', 'UBICAR', 'UMBRAL', 'UNICAS', 'UNICOS', 'UNIDAD',
  'UNIDAS', 'UNIDOS', 'URBANA', 'URBANO', 'USADAS', 'USADOS',
  'UTILES', 'VALIDA', 'VALIDO', 'VALORA', 'VARIOS',
  'VECINA', 'VECINO', 'VEINTE', 'VELADA', 'VENCER',
  'VENDER', 'VENENO', 'VENGAN', 'VENTAS', 'VERDAD',
  'VERDES', 'VERSAR', 'VERSOS', 'VIAJAR', 'VIAJES', 'VICTOR', 'VIDEOS',
  'VIENEN', 'VIENTO', 'VIOLET', 'VIRGEN',
  'VIRTUD', 'VISITA', 'VISTAS', 'VISUAL', 'VUELTAS', 'ZONAS'
]);

function getSpainDate() {
  // Always use Madrid timezone for consistent daily reset at midnight Spain time
  const spain = new Date().toLocaleDateString('en-CA', { timeZone: 'Europe/Madrid' });
  const [year, month, day] = spain.split('-').map(Number);
  return { year, month, day };
}

function getTodayKey() {
  const { year, month, day } = getSpainDate();
  return `${year}-${String(month).padStart(2, '0')}-${String(day).padStart(2, '0')}`;
}

function getDailyWord() {
  const { year, month, day } = getSpainDate();
  let seed = year * 10000 + month * 100 + day;
  // Scramble seed to avoid sequential word selection (must match frontend)
  seed = ((seed * 1103515245 + 12345) >>> 0) % 2147483648;
  const idx = seed % WORDS_CLEAN.length;
  return WORDS_CLEAN[idx];
}

// ==================== INITIALIZATION ====================
function init(io) {
  console.log('SQRRRDLE handler initialized');
}

// ==================== SOCKET HANDLERS ====================
function setupHandlers(io, socket, context) {
  const { getUser, saveUser, getLoggedInUsername } = context;

  // Get current game state for the user (syncs across devices)
  socket.on('sqrrrdle:getState', () => {
    const username = getLoggedInUsername();
    if (!username) {
      socket.emit('sqrrrdle:error', { message: 'No has iniciado sesión' });
      return;
    }

    const user = getUser(username);
    if (!user) {
      socket.emit('sqrrrdle:error', { message: 'Usuario no encontrado' });
      return;
    }

    // Initialize sqrrrdle stats if not present
    if (!user.sqrrrdle) {
      user.sqrrrdle = {
        wordsGuessed: 0,
        totalTries: 0,
        totalCoins: 0,
        lastCompletedDate: null,
        currentDayGuesses: [],
        currentDayStatus: 'playing',
        currentDayKey: null
      };
    }

    const todayKey = getTodayKey();

    // Check if it's a new day - only reset if currentDayKey exists AND is different
    // This prevents resetting when currentDayKey is null/undefined (migration from old data)
    if (user.sqrrrdle.currentDayKey && user.sqrrrdle.currentDayKey !== todayKey) {
      // It's a new day, reset daily state
      user.sqrrrdle.currentDayGuesses = [];
      user.sqrrrdle.currentDayStatus = 'playing';
    }
    // Always ensure currentDayKey is set to today
    if (user.sqrrrdle.currentDayKey !== todayKey) {
      user.sqrrrdle.currentDayKey = todayKey;
      saveUser(username);
    }

    socket.emit('sqrrrdle:state', {
      guesses: user.sqrrrdle.currentDayGuesses || [],
      status: user.sqrrrdle.currentDayStatus || 'playing',
      coins: user.coins ?? 1000,
      todayKey: todayKey,
      stats: {
        wordsGuessed: user.sqrrrdle.wordsGuessed || 0,
        totalTries: user.sqrrrdle.totalTries || 0,
        totalCoins: user.sqrrrdle.totalCoins || 0
      }
    });
  });

  // Submit a guess
  socket.on('sqrrrdle:guess', (data) => {
    const username = getLoggedInUsername();
    if (!username) {
      socket.emit('sqrrrdle:error', { message: 'No has iniciado sesión' });
      return;
    }

    // Prevent race condition
    if (userLocks.get(username)) {
      socket.emit('sqrrrdle:error', { message: 'Procesando operación anterior...' });
      return;
    }

    const user = getUser(username);
    if (!user) {
      socket.emit('sqrrrdle:error', { message: 'Usuario no encontrado' });
      return;
    }

    const guess = (data?.guess || '').toUpperCase().trim();
    const targetWord = getDailyWord();
    const expectedLength = targetWord.length;
    if (guess.length !== expectedLength) {
      socket.emit('sqrrrdle:error', { message: `La palabra debe tener ${expectedLength} letras` });
      return;
    }

    // Validate word is in our dictionary
    if (!VALID_GUESSES.has(guess)) {
      socket.emit('sqrrrdle:error', { message: 'Palabra no válida' });
      return;
    }

    // Initialize sqrrrdle stats if not present
    if (!user.sqrrrdle) {
      user.sqrrrdle = {
        wordsGuessed: 0,
        totalTries: 0,
        totalCoins: 0,
        lastCompletedDate: null,
        currentDayGuesses: [],
        currentDayStatus: 'playing',
        currentDayKey: null
      };
    }

    const todayKey = getTodayKey();

    // Check if it's a new day - only reset if currentDayKey exists AND is different
    if (user.sqrrrdle.currentDayKey && user.sqrrrdle.currentDayKey !== todayKey) {
      user.sqrrrdle.currentDayGuesses = [];
      user.sqrrrdle.currentDayStatus = 'playing';
    }
    // Always ensure currentDayKey is set to today
    user.sqrrrdle.currentDayKey = todayKey;

    // Check if already completed today
    if (user.sqrrrdle.currentDayStatus === 'won' || user.sqrrrdle.currentDayStatus === 'lost') {
      socket.emit('sqrrrdle:error', { message: 'Ya completaste el SQRRRDLE de hoy' });
      return;
    }

    // Check if too many guesses
    if ((user.sqrrrdle.currentDayGuesses || []).length >= 6) {
      socket.emit('sqrrrdle:error', { message: 'Ya usaste todos tus intentos' });
      return;
    }

    // Lock user during transaction
    userLocks.set(username, true);

    try {
      // Add guess to list
      user.sqrrrdle.currentDayGuesses = user.sqrrrdle.currentDayGuesses || [];
      user.sqrrrdle.currentDayGuesses.push(guess);
      user.sqrrrdle.totalTries = (user.sqrrrdle.totalTries || 0) + 1;

      const attempts = user.sqrrrdle.currentDayGuesses.length;
      const isCorrect = guess === targetWord;
      const isGameOver = isCorrect || attempts >= 6;

      let payout = 0;

      if (isCorrect) {
        // Calculate payout: 5000 for first 3 tries, 1000 after
        payout = attempts <= 3 ? 5000 : 1000;

        // Award payout
        user.coins = (user.coins ?? 1000) + payout;

        // Update stats
        user.sqrrrdle.wordsGuessed = (user.sqrrrdle.wordsGuessed || 0) + 1;
        user.sqrrrdle.totalCoins = (user.sqrrrdle.totalCoins || 0) + payout;
        user.sqrrrdle.lastCompletedDate = todayKey;
        user.sqrrrdle.currentDayStatus = 'won';

        console.log(`[SQRRRDLE] ${username} ganó en ${attempts} intentos. Recompensa: ${payout}. Balance: ${user.coins}`);
      } else if (isGameOver) {
        // Lost - mark as completed with no reward
        user.sqrrrdle.lastCompletedDate = todayKey;
        user.sqrrrdle.currentDayStatus = 'lost';

        console.log(`[SQRRRDLE] ${username} perdió. La palabra era: ${targetWord}`);
      }

      saveUser(username);

      // Send response
      socket.emit('sqrrrdle:guessResult', {
        guess,
        isCorrect,
        isGameOver,
        payout,
        coins: user.coins,
        attempts,
        targetWord: isGameOver ? targetWord : null,
        status: user.sqrrrdle.currentDayStatus
      });

      // Also emit general coin update if payout
      if (payout > 0) {
        socket.emit('user:coins', {
          coins: user.coins
        });
      }
    } finally {
      userLocks.delete(username);
    }
  });

  // Player won wordle - legacy endpoint (kept for backward compatibility)
  socket.on('wordle:win', (data) => {
    const username = getLoggedInUsername();
    if (!username) {
      socket.emit('wordle:error', { message: 'Not logged in' });
      return;
    }

    // Prevent race condition
    if (userLocks.get(username)) {
      socket.emit('wordle:error', { message: 'Procesando operación anterior...' });
      return;
    }

    const user = getUser(username);
    if (!user) {
      socket.emit('wordle:error', { message: 'User not found' });
      return;
    }

    const attempts = parseInt(data?.attempts) || 6;
    if (attempts < 1 || attempts > 6) {
      socket.emit('wordle:error', { message: 'Invalid attempts' });
      return;
    }

    // Initialize sqrrrdle stats if not present
    if (!user.sqrrrdle) {
      user.sqrrrdle = {
        wordsGuessed: 0,
        totalTries: 0,
        totalCoins: 0,
        lastCompletedDate: null,
        currentDayGuesses: [],
        currentDayStatus: 'playing'
      };
    }

    const todayKey = getTodayKey();

    // Check if already completed today
    if (user.sqrrrdle.lastCompletedDate === todayKey) {
      socket.emit('wordle:error', { message: 'Ya jugaste hoy' });
      return;
    }

    // Lock user during transaction
    userLocks.set(username, true);

    try {
      // Calculate payout: 5000 for first 3 tries, 1000 after
      const payout = attempts <= 3 ? 5000 : 1000;

      // Award payout
      user.coins = (user.coins ?? 1000) + payout;

      // Track sqrrrdle stats
      user.sqrrrdle.wordsGuessed = (user.sqrrrdle.wordsGuessed || 0) + 1;
      user.sqrrrdle.totalTries = (user.sqrrrdle.totalTries || 0) + attempts;
      user.sqrrrdle.totalCoins = (user.sqrrrdle.totalCoins || 0) + payout;
      user.sqrrrdle.lastCompletedDate = todayKey;
      user.sqrrrdle.currentDayStatus = 'won';

      saveUser(username);

      console.log(`[SQRRRDLE] ${username} ganó en ${attempts} intentos. Recompensa: ${payout}. Balance: ${user.coins}`);

      socket.emit('wordle:coins', {
        payout,
        coins: user.coins
      });

      // Also emit general coin update
      socket.emit('user:coins', {
        coins: user.coins
      });
    } finally {
      userLocks.delete(username);
    }
  });

  // Cleanup function
  return {
    handleDisconnect: () => {
      // No cleanup needed for sqrrrdle
    }
  };
}

module.exports = {
  init,
  setupHandlers
};
